# Generated by Django 4.0.3 on 2022-06-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2022-05-17'),
        ),
    ]
