# Generated by Django 4.0.3 on 2022-06-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin_student', '0003_remove_results_student_id_remove_results_subject_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('grade', models.IntegerField(max_length=2)),
                ('email', models.EmailField(max_length=150)),
            ],
        ),
    ]
