# Generated by Django 4.0.3 on 2022-06-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
